import java.util.Scanner;

public class ExceptionMethods 
{

	public static void main(String[] args) 
	{
		ExceptionMethods em = new ExceptionMethods (); 
		em.divide();
		System.out.println("Check Me");	 

	}
	private void divide()
	{
		Scanner sc = new Scanner(System.in);
	    System.out.println("Enter two numbers ");
	    
	    int no1 = sc.nextInt();
	    int no2 = sc.nextInt();
	    
	    try 
	    {
	      System.out.println(no1/no2);
	      int[] ar = new int[no2];
	      
	      for(int i=0; i<ar.length; i++)
	      {
	        System.out.println(ar[i]);
	      }
	      
	    }
	    catch(ArithmeticException ae)
	    {
	    	
	    // ------- Important Methods ------------ // 
	    	
	      ae.printStackTrace();
	      
		  System.out.println(ae.getMessage());
		  
		  System.out.println(ae.getClass().getName());
		  
	      System.out.println("Check Divisor");
	    }
	    catch(NegativeArraySizeException nnn)
	    {
	      System.out.println("Array size should not be negative");
	      
	    }
	    finally
	    {
	      System.out.println("DB Connected ");
	      System.out.println("Disconnecting DB");
	    }

	}

}

